apiVersion: apps/v1
kind: Deployment
metadata:
  name: vproapp
  labels:
    app: vproapp

spec:
  replicas: 1
  selector:
    matchLabels:
      app: vproapp
  template:
    metadata:
      labels:
        app: vproapp

    spec:
      affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - vproapp
                  - vprodb
                  - vpromc
                  - vprormq
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: vproapp
        image: vprocontainers/vprofileapp
        ports:
        - containerPort: 8080
          name: vproapp-port

      initContainers:
      - name: init-mydb
        image: busybox
        command: ['sh', '-c', "until nslookup vprodb.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for vprodb; sleep 2; done"]
      - name: init-memcache
        image: busybox
        command: ['sh', '-c', "until nslookup vprocache01.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for vprocache; sleep 2; done"]
      - name: init-rabbitmq
        image: busybox

        command: ['sh', '-c', "until nslookup vpromq01.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for vpromq; sleep 2; done"]
