apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprormq
  labels: 
    app: vprormq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vprormq
  template:
    metadata:
      labels:
        app: vprormq
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - vproapp
                - vprodb
                - vpromc
                - vprormq
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: vprormq
        image: rabbitmq:latest
        ports:
        - name: vprormq-port
          containerPort: 5672
        env:
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: rmq-pass
        - name: RABBITMQ_DEFAULT_USER
          value: "guest"

